# See reference docs for details:
# https://config.travis-ci.com.
dist: bionic

services:
  - docker

language: go
go: 1.14.x

addons:
  apt:
    packages:
      - make

jobs:
  include:
    - stage: Linux
      os: linux
      script:
        - ./scripts/travis-ci.sh ci
        - ./scripts/travis-ci.sh android
        - ./scripts/travis-ci.sh qt-linux
        - ./scripts/travis_upload_nightlies.sh
    - stage: macOS
      os: osx
      script:
        - ./scripts/travis-ci.sh qt-osx
        - ./scripts/travis_upload_nightlies.sh
